configuration:
  initialization:
    script: init.sh
  start:
    script: start.sh
  healthcheck:
    wait_for_ports: 80
    timeout: 360
source:
  image:
    ami:
    - id: ami-f90a4880
      region: eu-west-1
  os_type: linux
infrastructure:
  connectivity:
    external:
    - port_info:
        port: 80
        path: ''
inputs:
  - VERSION
  - COLOR
debugging:
  connection_protocol: SSH
kind: application
spec_version: 1